import { chromium } from 'playwright';
const b=await chromium.launch(); const p=await(await b.newContext({viewport:{width:1400,height:900}})).newPage();
const msgs=[]; p.on('console',m=>{ const t=m.text(); if(t.includes('[RZm]')) msgs.push(t); });
await p.goto('http://localhost:4300/components/grid',{waitUntil:'networkidle'}); await p.waitForTimeout(2500);
const header = p.locator('cw-grid [role="columnheader"]', {hasText:'Name'}).first();
const rb = await header.locator('.column-resizer').first().boundingBox();
await p.mouse.move(rb.x+3, rb.y+3); await p.mouse.down();
await p.mouse.move(rb.x+120, rb.y+200, {steps:10});
await p.mouse.up(); await p.waitForTimeout(300);
const endW = await header.evaluate(el=>Math.round(el.getBoundingClientRect().width));
console.log('total [RZm] messages:', msgs.length);
msgs.forEach(m=>console.log('  '+m));
console.log('endW:', endW);
await b.close();
