import { Routes } from '@angular/router';
import { GRID_FEATURES } from './showcase/grid-features';

export const routes: Routes = [
  { path: '', pathMatch: 'full', loadComponent: () => import('./pages/overview.component').then(m => m.OverviewComponent) },
  { path: 'grid', pathMatch: 'full', redirectTo: 'grid/basic' },
  ...GRID_FEATURES.map(f => ({
    path: f.path,
    loadComponent: () => import('./pages/grid-demo/grid-feature.component').then(m => m.GridFeaturePageComponent),
    data: { feature: f.feature, title: f.title, description: f.description }
  })),
  { path: 'button', loadComponent: () => import('./pages/button-demo.component').then(m => m.ButtonDemoComponent) },
  { path: 'select', loadComponent: () => import('./pages/select-demo.component').then(m => m.SelectDemoComponent) },
  { path: 'checkbox', loadComponent: () => import('./pages/checkbox-demo.component').then(m => m.CheckboxDemoComponent) },
  { path: 'radio-button', loadComponent: () => import('./pages/radio-button-demo.component').then(m => m.RadioButtonDemoComponent) },
  { path: 'toggle-switch', loadComponent: () => import('./pages/toggle-switch-demo.component').then(m => m.ToggleSwitchDemoComponent) },
  { path: 'rating', loadComponent: () => import('./pages/rating-demo.component').then(m => m.RatingDemoComponent) },
  { path: 'chip', loadComponent: () => import('./pages/chip-demo.component').then(m => m.ChipDemoComponent) },
  { path: 'divider', loadComponent: () => import('./pages/divider-demo.component').then(m => m.DividerDemoComponent) },
  { path: 'alert', loadComponent: () => import('./pages/alert-demo.component').then(m => m.AlertDemoComponent) },
  { path: 'accordion', loadComponent: () => import('./pages/accordion-demo.component').then(m => m.AccordionDemoComponent) },
  { path: 'tabs', loadComponent: () => import('./pages/tabs-demo.component').then(m => m.TabsDemoComponent) },
  { path: 'breadcrumb', loadComponent: () => import('./pages/breadcrumb-demo.component').then(m => m.BreadcrumbDemoComponent) },
  { path: 'tooltip', loadComponent: () => import('./pages/tooltip-demo.component').then(m => m.TooltipDemoComponent) },
  { path: 'slider', loadComponent: () => import('./pages/slider-demo.component').then(m => m.SliderDemoComponent) },
  { path: 'input-text', loadComponent: () => import('./pages/input-text-demo.component').then(m => m.InputTextDemoComponent) },
  { path: 'multi-select', loadComponent: () => import('./pages/multi-select-demo.component').then(m => m.MultiSelectDemoComponent) },
  { path: 'paginator', loadComponent: () => import('./pages/paginator-demo.component').then(m => m.PaginatorDemoComponent) },
  { path: 'steps', loadComponent: () => import('./pages/steps-demo.component').then(m => m.StepsDemoComponent) },
  { path: 'menu', loadComponent: () => import('./pages/menu-demo.component').then(m => m.MenuDemoComponent) },
  { path: 'dialog', loadComponent: () => import('./pages/dialog-demo.component').then(m => m.DialogDemoComponent) },
  { path: 'date-picker', loadComponent: () => import('./pages/date-picker-demo.component').then(m => m.DatePickerDemoComponent) },
  { path: 'card', loadComponent: () => import('./pages/card-demo.component').then(m => m.CardDemoComponent) },
  { path: 'select-button', loadComponent: () => import('./pages/select-button-demo.component').then(m => m.SelectButtonDemoComponent) },
  { path: 'listbox', loadComponent: () => import('./pages/listbox-demo.component').then(m => m.ListboxDemoComponent) },
  { path: 'badge', loadComponent: () => import('./pages/badge-demo.component').then(m => m.BadgeDemoComponent) },
  { path: 'tag', loadComponent: () => import('./pages/tag-demo.component').then(m => m.TagDemoComponent) },
  { path: 'avatar', loadComponent: () => import('./pages/avatar-demo.component').then(m => m.AvatarDemoComponent) },
  { path: 'spinner', loadComponent: () => import('./pages/spinner-demo.component').then(m => m.SpinnerDemoComponent) },
  { path: 'progress-bar', loadComponent: () => import('./pages/progress-bar-demo.component').then(m => m.ProgressBarDemoComponent) },
  { path: 'skeleton', loadComponent: () => import('./pages/skeleton-demo.component').then(m => m.SkeletonDemoComponent) },
  { path: 'popover', loadComponent: () => import('./pages/popover-demo.component').then(m => m.PopoverDemoComponent) },
  { path: 'autocomplete', loadComponent: () => import('./pages/autocomplete-demo.component').then(m => m.AutoCompleteDemoComponent) },
  { path: 'toast', loadComponent: () => import('./pages/toast-demo.component').then(m => m.ToastDemoComponent) },
  { path: 'confirm', loadComponent: () => import('./pages/confirm-demo.component').then(m => m.ConfirmDemoComponent) },
  { path: 'drawer', loadComponent: () => import('./pages/drawer-demo.component').then(m => m.DrawerDemoComponent) },
  { path: 'context-menu', loadComponent: () => import('./pages/context-menu-demo.component').then(m => m.ContextMenuDemoComponent) },
  { path: 'tree', loadComponent: () => import('./pages/tree-demo.component').then(m => m.TreeDemoComponent) },
  { path: 'input-number', loadComponent: () => import('./pages/input-number-demo.component').then(m => m.InputNumberDemoComponent) },
  { path: 'password', loadComponent: () => import('./pages/password-demo.component').then(m => m.PasswordDemoComponent) },
  { path: 'timeline', loadComponent: () => import('./pages/timeline-demo.component').then(m => m.TimelineDemoComponent) },
  { path: 'knob', loadComponent: () => import('./pages/knob-demo.component').then(m => m.KnobDemoComponent) },
  { path: 'menubar', loadComponent: () => import('./pages/menubar-demo.component').then(m => m.MenubarDemoComponent) },
  { path: 'order-list', loadComponent: () => import('./pages/order-list-demo.component').then(m => m.OrderListDemoComponent) },
  { path: 'panel-menu', loadComponent: () => import('./pages/panel-menu-demo.component').then(m => m.PanelMenuDemoComponent) },
  { path: 'color-picker', loadComponent: () => import('./pages/color-picker-demo.component').then(m => m.ColorPickerDemoComponent) },
  { path: 'input-otp', loadComponent: () => import('./pages/input-otp-demo.component').then(m => m.InputOtpDemoComponent) },
  { path: 'meter-group', loadComponent: () => import('./pages/meter-group-demo.component').then(m => m.MeterGroupDemoComponent) },
  { path: 'scroll-top', loadComponent: () => import('./pages/scroll-top-demo.component').then(m => m.ScrollTopDemoComponent) },
  { path: 'pick-list', loadComponent: () => import('./pages/pick-list-demo.component').then(m => m.PickListDemoComponent) },
  { path: 'carousel', loadComponent: () => import('./pages/carousel-demo.component').then(m => m.CarouselDemoComponent) },
  { path: 'fieldset', loadComponent: () => import('./pages/fieldset-demo.component').then(m => m.FieldsetDemoComponent) },
  { path: 'inplace', loadComponent: () => import('./pages/inplace-demo.component').then(m => m.InplaceDemoComponent) },
  { path: 'speed-dial', loadComponent: () => import('./pages/speed-dial-demo.component').then(m => m.SpeedDialDemoComponent) },
  { path: 'block-ui', loadComponent: () => import('./pages/block-ui-demo.component').then(m => m.BlockUiDemoComponent) },
  { path: 'data-view', loadComponent: () => import('./pages/data-view-demo.component').then(m => m.DataViewDemoComponent) },
  { path: 'textarea', loadComponent: () => import('./pages/textarea-demo.component').then(m => m.TextareaDemoComponent) },
  { path: 'input-mask', loadComponent: () => import('./pages/input-mask-demo.component').then(m => m.InputMaskDemoComponent) },
  { path: 'splitter', loadComponent: () => import('./pages/splitter-demo.component').then(m => m.SplitterDemoComponent) },
  { path: 'image', loadComponent: () => import('./pages/image-demo.component').then(m => m.ImageDemoComponent) },
  { path: 'dock', loadComponent: () => import('./pages/dock-demo.component').then(m => m.DockDemoComponent) },
  { path: 'stepper', loadComponent: () => import('./pages/stepper-demo.component').then(m => m.StepperDemoComponent) },
  { path: 'tiered-menu', loadComponent: () => import('./pages/tiered-menu-demo.component').then(m => m.TieredMenuDemoComponent) },
  { path: 'scroll-panel', loadComponent: () => import('./pages/scroll-panel-demo.component').then(m => m.ScrollPanelDemoComponent) },
  { path: 'input-group', loadComponent: () => import('./pages/input-group-demo.component').then(m => m.InputGroupDemoComponent) },
  { path: 'float-label', loadComponent: () => import('./pages/float-label-demo.component').then(m => m.FloatLabelDemoComponent) },
  { path: 'galleria', loadComponent: () => import('./pages/galleria-demo.component').then(m => m.GalleriaDemoComponent) },
  { path: '**', redirectTo: '' }
];
