import { Routes } from '@angular/router';

export const routes: Routes = [
  {
    path: '',
    pathMatch: 'full',
    loadComponent: () => import('./pages/home.component').then(m => m.HomeComponent)
  },
  {
    path: 'app',
    loadComponent: () => import('./demo-app/demo-shell.component').then(m => m.DemoShellComponent),
    children: [
      { path: '', pathMatch: 'full', redirectTo: 'dashboard' },
      { path: 'dashboard', loadComponent: () => import('./demo-app/dashboard.component').then(m => m.DemoDashboardComponent) },
      { path: 'products', loadComponent: () => import('./demo-app/products.component').then(m => m.DemoProductsComponent) },
      { path: 'customers', loadComponent: () => import('./demo-app/customers.component').then(m => m.DemoCustomersComponent) },
      { path: 'profile', loadComponent: () => import('./demo-app/profile.component').then(m => m.DemoProfileComponent) }
    ]
  },
  {
    path: 'components',
    loadComponent: () => import('./pages/components-layout.component').then(m => m.ComponentsLayoutComponent),
    children: [
      { path: '', pathMatch: 'full', loadComponent: () => import('./pages/gallery.component').then(m => m.GalleryComponent) },

      // Built documentation pages.
      { path: 'grid', loadComponent: () => import('./pages/docs/grid.doc').then(m => m.GridDocComponent) },
      { path: 'table', loadComponent: () => import('./pages/docs/table.doc').then(m => m.TableDocComponent) },
      { path: 'button', loadComponent: () => import('./pages/docs/button.doc').then(m => m.ButtonDocComponent) },
      { path: 'org-chart', loadComponent: () => import('./pages/docs/org-chart.doc').then(m => m.OrgChartDocComponent) },
      { path: 'input-number', loadComponent: () => import('./pages/docs/input-number.doc').then(m => m.InputNumberDocComponent) },
      { path: 'date-picker', loadComponent: () => import('./pages/docs/date-picker.doc').then(m => m.DatePickerDocComponent) },
      { path: 'select', loadComponent: () => import('./pages/docs/select.doc').then(m => m.SelectDocComponent) },
      { path: 'multi-select', loadComponent: () => import('./pages/docs/multi-select.doc').then(m => m.MultiSelectDocComponent) },
      { path: 'autocomplete', loadComponent: () => import('./pages/docs/autocomplete.doc').then(m => m.AutoCompleteDocComponent) },
      { path: 'tree', loadComponent: () => import('./pages/docs/tree.doc').then(m => m.TreeDocComponent) },
      { path: 'stepper', loadComponent: () => import('./pages/docs/stepper.doc').then(m => m.StepperDocComponent) },
      { path: 'dialog', loadComponent: () => import('./pages/docs/dialog.doc').then(m => m.DialogDocComponent) },

      { path: 'accordion', loadComponent: () => import('./pages/docs/accordion.doc').then(m => m.AccordionDocComponent) },
      { path: 'alert', loadComponent: () => import('./pages/docs/alert.doc').then(m => m.AlertDocComponent) },
      { path: 'animate-on-scroll', loadComponent: () => import('./pages/docs/animate-on-scroll.doc').then(m => m.AnimateOnScrollDocComponent) },
      { path: 'avatar', loadComponent: () => import('./pages/docs/avatar.doc').then(m => m.AvatarDocComponent) },
      { path: 'badge', loadComponent: () => import('./pages/docs/badge.doc').then(m => m.BadgeDocComponent) },
      { path: 'block-ui', loadComponent: () => import('./pages/docs/block-ui.doc').then(m => m.BlockUiDocComponent) },
      { path: 'breadcrumb', loadComponent: () => import('./pages/docs/breadcrumb.doc').then(m => m.BreadcrumbDocComponent) },
      { path: 'card', loadComponent: () => import('./pages/docs/card.doc').then(m => m.CardDocComponent) },
      { path: 'carousel', loadComponent: () => import('./pages/docs/carousel.doc').then(m => m.CarouselDocComponent) },
      { path: 'checkbox', loadComponent: () => import('./pages/docs/checkbox.doc').then(m => m.CheckboxDocComponent) },
      { path: 'chip', loadComponent: () => import('./pages/docs/chip.doc').then(m => m.ChipDocComponent) },
      { path: 'color-picker', loadComponent: () => import('./pages/docs/color-picker.doc').then(m => m.ColorPickerDocComponent) },
      { path: 'confirm', loadComponent: () => import('./pages/docs/confirm.doc').then(m => m.ConfirmDocComponent) },
      { path: 'context-menu', loadComponent: () => import('./pages/docs/context-menu.doc').then(m => m.ContextMenuDocComponent) },
      { path: 'data-view', loadComponent: () => import('./pages/docs/data-view.doc').then(m => m.DataViewDocComponent) },
      { path: 'deferred-content', loadComponent: () => import('./pages/docs/deferred-content.doc').then(m => m.DeferredContentDocComponent) },
      { path: 'divider', loadComponent: () => import('./pages/docs/divider.doc').then(m => m.DividerDocComponent) },
      { path: 'dock', loadComponent: () => import('./pages/docs/dock.doc').then(m => m.DockDocComponent) },
      { path: 'drawer', loadComponent: () => import('./pages/docs/drawer.doc').then(m => m.DrawerDocComponent) },
      { path: 'dynamic-dialog', loadComponent: () => import('./pages/docs/dynamic-dialog.doc').then(m => m.DynamicDialogDocComponent) },
      { path: 'editor', loadComponent: () => import('./pages/docs/editor.doc').then(m => m.EditorDocComponent) },
      { path: 'fieldset', loadComponent: () => import('./pages/docs/fieldset.doc').then(m => m.FieldsetDocComponent) },
      { path: 'float-label', loadComponent: () => import('./pages/docs/float-label.doc').then(m => m.FloatLabelDocComponent) },
      { path: 'focus-trap', loadComponent: () => import('./pages/docs/focus-trap.doc').then(m => m.FocusTrapDocComponent) },
      { path: 'galleria', loadComponent: () => import('./pages/docs/galleria.doc').then(m => m.GalleriaDocComponent) },
      { path: 'ifta-label', loadComponent: () => import('./pages/docs/ifta-label.doc').then(m => m.IftaLabelDocComponent) },
      { path: 'image', loadComponent: () => import('./pages/docs/image.doc').then(m => m.ImageDocComponent) },
      { path: 'inplace', loadComponent: () => import('./pages/docs/inplace.doc').then(m => m.InplaceDocComponent) },
      { path: 'input-group', loadComponent: () => import('./pages/docs/input-group.doc').then(m => m.InputGroupDocComponent) },
      { path: 'input-mask', loadComponent: () => import('./pages/docs/input-mask.doc').then(m => m.InputMaskDocComponent) },
      { path: 'input-otp', loadComponent: () => import('./pages/docs/input-otp.doc').then(m => m.InputOtpDocComponent) },
      { path: 'input-text', loadComponent: () => import('./pages/docs/input-text.doc').then(m => m.InputTextDocComponent) },
      { path: 'knob', loadComponent: () => import('./pages/docs/knob.doc').then(m => m.KnobDocComponent) },
      { path: 'listbox', loadComponent: () => import('./pages/docs/listbox.doc').then(m => m.ListboxDocComponent) },
      { path: 'mega-menu', loadComponent: () => import('./pages/docs/mega-menu.doc').then(m => m.MegaMenuDocComponent) },
      { path: 'menu', loadComponent: () => import('./pages/docs/menu.doc').then(m => m.MenuDocComponent) },
      { path: 'menubar', loadComponent: () => import('./pages/docs/menubar.doc').then(m => m.MenubarDocComponent) },
      { path: 'meter-group', loadComponent: () => import('./pages/docs/meter-group.doc').then(m => m.MeterGroupDocComponent) },
      { path: 'order-list', loadComponent: () => import('./pages/docs/order-list.doc').then(m => m.OrderListDocComponent) },
      { path: 'paginator', loadComponent: () => import('./pages/docs/paginator.doc').then(m => m.PaginatorDocComponent) },
      { path: 'panel-menu', loadComponent: () => import('./pages/docs/panel-menu.doc').then(m => m.PanelMenuDocComponent) },
      { path: 'password', loadComponent: () => import('./pages/docs/password.doc').then(m => m.PasswordDocComponent) },
      { path: 'pick-list', loadComponent: () => import('./pages/docs/pick-list.doc').then(m => m.PickListDocComponent) },
      { path: 'popover', loadComponent: () => import('./pages/docs/popover.doc').then(m => m.PopoverDocComponent) },
      { path: 'progress-bar', loadComponent: () => import('./pages/docs/progress-bar.doc').then(m => m.ProgressBarDocComponent) },
      { path: 'radio-button', loadComponent: () => import('./pages/docs/radio-button.doc').then(m => m.RadioButtonDocComponent) },
      { path: 'rating', loadComponent: () => import('./pages/docs/rating.doc').then(m => m.RatingDocComponent) },
      { path: 'ripple', loadComponent: () => import('./pages/docs/ripple.doc').then(m => m.RippleDocComponent) },
      { path: 'scroll-panel', loadComponent: () => import('./pages/docs/scroll-panel.doc').then(m => m.ScrollPanelDocComponent) },
      { path: 'scroll-top', loadComponent: () => import('./pages/docs/scroll-top.doc').then(m => m.ScrollTopDocComponent) },
      { path: 'select-button', loadComponent: () => import('./pages/docs/select-button.doc').then(m => m.SelectButtonDocComponent) },
      { path: 'skeleton', loadComponent: () => import('./pages/docs/skeleton.doc').then(m => m.SkeletonDocComponent) },
      { path: 'slider', loadComponent: () => import('./pages/docs/slider.doc').then(m => m.SliderDocComponent) },
      { path: 'speed-dial', loadComponent: () => import('./pages/docs/speed-dial.doc').then(m => m.SpeedDialDocComponent) },
      { path: 'spinner', loadComponent: () => import('./pages/docs/spinner.doc').then(m => m.SpinnerDocComponent) },
      { path: 'splitter', loadComponent: () => import('./pages/docs/splitter.doc').then(m => m.SplitterDocComponent) },
      { path: 'steps', loadComponent: () => import('./pages/docs/steps.doc').then(m => m.StepsDocComponent) },
      { path: 'style-class', loadComponent: () => import('./pages/docs/style-class.doc').then(m => m.StyleClassDocComponent) },
      { path: 'tabs', loadComponent: () => import('./pages/docs/tabs.doc').then(m => m.TabsDocComponent) },
      { path: 'tag', loadComponent: () => import('./pages/docs/tag.doc').then(m => m.TagDocComponent) },
      { path: 'terminal', loadComponent: () => import('./pages/docs/terminal.doc').then(m => m.TerminalDocComponent) },
      { path: 'textarea', loadComponent: () => import('./pages/docs/textarea.doc').then(m => m.TextareaDocComponent) },
      { path: 'tiered-menu', loadComponent: () => import('./pages/docs/tiered-menu.doc').then(m => m.TieredMenuDocComponent) },
      { path: 'timeline', loadComponent: () => import('./pages/docs/timeline.doc').then(m => m.TimelineDocComponent) },
      { path: 'toast', loadComponent: () => import('./pages/docs/toast.doc').then(m => m.ToastDocComponent) },
      { path: 'toggle-switch', loadComponent: () => import('./pages/docs/toggle-switch.doc').then(m => m.ToggleSwitchDocComponent) },
      { path: 'tooltip', loadComponent: () => import('./pages/docs/tooltip.doc').then(m => m.TooltipDocComponent) },
      { path: 'virtual-scroller', loadComponent: () => import('./pages/docs/virtual-scroller.doc').then(m => m.VirtualScrollerDocComponent) },

      // Everything else: a "coming soon" placeholder (still routable from the sidebar/gallery).
      { path: ':slug', loadComponent: () => import('./pages/coming-soon.component').then(m => m.ComingSoonComponent) }
    ]
  },
  { path: '**', redirectTo: '' }
];
